const FETCH_EDIT_POST_STARTED = "[edit-post]/FETCH_EDIT_POST_STARTED";
const FETCH_EDIT_POST_SUCCEDED = "[edit-post]/FETCH_EDIT_POST_SUCCEDED";
const FETCH_EDIT_POST_FAILED = "[edit-post]/FETCH_EDIT_POST_FAILED";
const SET_EDITED_POST_TO_DEFAULT = "[edit-post]/SET_EDITED_POST_TO_DEFAULT";


export default {
    FETCH_EDIT_POST_STARTED, FETCH_EDIT_POST_SUCCEDED,
    FETCH_EDIT_POST_FAILED, SET_EDITED_POST_TO_DEFAULT
}