const FETCH_LIST_POSTS_SUCCEEDED = '[list-posts]/FETCH_LIST_POSTS_SUCCEEDED';
const FETCH_LIST_POSTS_STARTED = '[list-posts]/FETCH_LIST_POSTS_STARTED';
const FETCH_LIST_POSTS_FAILED = '[list-posts]/FETCH_LIST_POSTS_FAILED';


export default { FETCH_LIST_POSTS_SUCCEEDED, FETCH_LIST_POSTS_FAILED, FETCH_LIST_POSTS_STARTED }