const SHOW_REVERT = "[revert]/SHOW_REVERT";
const CLOSE_REVERT = "[revert]/CLOSE_REVERT";
const TOGGLE_REVERT = "[revert]/TOGGLE_REVERT";

const SET_REVERT_OPERATHION_METHOD = "[revert]/SET_REVERT_OPERATHION_METHOD";

const FETCH_REVERT_STARTED = "[revert]/FETCH_REVERT_STARTED";
const FETCH_REVERT_SUCCEDED = "[revert]/FETCH_REVERT_SUCCEDED";

export default {
  SHOW_REVERT,
  CLOSE_REVERT,
  TOGGLE_REVERT,
  SET_REVERT_OPERATHION_METHOD,
  FETCH_REVERT_STARTED,
  FETCH_REVERT_SUCCEDED
};
