const AUTH_REQUEST_TOKEN_STARTED = '[auth]/AUTH_REQUEST_TOKEN_STARTED';
const AUTH_REQUEST_TOKEN_SUCCED = '[auth]/AUTH_REQUEST_TOKEN_SUCCED';
const AUTH_REQUEST_TOKEN_FAILED = '[auth]/AUTH_REQUEST_TOKEN_FAILED';

export default {
    AUTH_REQUEST_TOKEN_STARTED, AUTH_REQUEST_TOKEN_SUCCED,
    AUTH_REQUEST_TOKEN_FAILED
}